# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('ci', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
